#!/bin/bash

cat << 'EOF'
AEROSPACE HOTKEYS

FOCUS
  alt-h/j/k/l              Focus left/down/up/right

MOVE WINDOW
  alt-shift-h/j/k/l        Move window left/down/up/right

WORKSPACE (GOTO)
  ctrl-1 to ctrl-9         Goto workspace 1-9
  ctrl-q then 0-9          Goto workspace 10-19
  ctrl-w then 0-9          Goto workspace 20-29

WORKSPACE (SEND WINDOW)
  ctrl-alt-1 to ctrl-alt-9 Send to workspace 1-9
  ctrl-alt-q then 0-9      Send to workspace 10-19
  ctrl-alt-w then 0-9      Send to workspace 20-29

LAYOUT
  alt-f                     Fullscreen
  alt-shift-space           Toggle floating/tiling
  alt-/                     Toggle tiles horizontal/vertical
  alt-,                     Toggle accordion horizontal/vertical
  alt-minus / alt-equal     Resize smaller/bigger
  alt-r then h/j/k/l       Resize mode

UTILITY
  alt-tab                   Workspace back-and-forth
  alt-shift-c               Reload config
  alt-shift-r               Reorganise all windows
EOF
